### ISSUE TITLE
How do I use keepmenu to copy password to clipboard ?

### ISSUE THREAD

**Issue by varac** [firecat53/keepmenu#19]
When I run `keepmenu` and select the wanted entry, `keepmenu` won't copy the password to the clipboard.
Instead, it will output the `USERNAMEPASSWORD` together, without a seperator.

How do I use `keepmenu` to *only* copy the password to the clipboard ?

**Comment by firecat53** [comment]
That's not a feature that's built in. In order to improve security, I chose to only use the pyuserinput typing function. There's no ability to copy to the clipboard, only type directly into a text input area.

**Comment by varac** [comment]
> In order to improve security, I chose to only use the pyuserinput typing function

Thats a nice intend but I think the result is counter-secure indeed. I already inserted my password into a shell, including a newline so they ended up in my ~/.zsh_history. I could have easily pasted them with this behaviour to a chat window if this would have been focussed.

So please implement the ability to copy it to the clipboard, like `gopass show --clip` does i.e.

Or pls document how to properly integrate it in i3/demu so passwords won't be inserted in the current focussed window.

**Comment by firecat53** [comment]
I'll entertain a pull request adding clipboard functionality, but I'm not intending to add that.

As to properly integrating...when you select an entry, it types the entry into the currently focused window by design. That's just the way it works. It's documented in the README. Even using a GUI password manager like Keepass works that way: when you type the hotkey to type the currently selected item, it types it into the currently selected field. It's just a training problem :smile:

**Comment by grininmonkey** [comment]
I agree with firecate53, I like the behavior and understood it before using it....
Being an i3 user myself, drun or rofi are blocking so its just a matter of making sure you do not loose focus on your target before launching.

I have accidentally Ctrl+V`ed into the wrong thing before when using normal keepass... so its not like clipboard is any safer..... in my opinion, provided you look at this great tool as a "clipboard output selector" ;-)

**Comment by varac** [comment]
Well, ppl are just used to different behaviour - and I wouldn't want to dictate my usage to other ppl.
And I don't see any value in a discussion which way is better.

That's why I opened this issue - and an alternative option to the default behavior.

Also, one of the problems of my initial issue description still not addressed is that:
> Instead, it will output the USERNAMEPASSWORD together, without a seperator.

Which I don't know how to solve neither.

**Comment by grininmonkey** [comment]
The default has the following setting...

 autotype_default = {USERNAME}{TAB}{PASSWORD}{ENTER}

I suppose that depending on where it's being populated, the tab is not presented?

**Comment by firecat53** [comment]
The tab will always be typed with that default sequence. What you are seeing when it types in a terminal is USERNAMEPASSWORD because in most shells, tab doesn't do anything unless you hit it twice (e.g. for bash completion). The default sequence is aimed primarily at web forms where tab moves between fields.
