### ISSUE TITLE
Notes field not functioning depending on editor

### ISSUE THREAD

**Issue by duckduck1** [firecat53/keepmenu#83]
I cannot view content of the Notes field with vim and cannot edit with geany. Both works fine with gvim.

Tested on Arch Linux (installed from AUR) with rofi set in config.

**Termite + vim**
`editor = vim`
`terminal = termite`
Vim does start without any file open.

**Geany (gui editor)**
`gui_editor = geany`
Geany does start with a *.tmp file open but keepmenu doesn't remember any changes made to the file.

**Gvim**
`editor = gvim -f`
Gvim does start with *.tmp file open and keepmenu remembers any changes made with gvim; working properly.

**Comment by firecat53** [comment]
Unfortunately, these two issues aren't ones I could easily fix in keepmenu.

1. Geany doesn't appear to have a 'keep in foreground' option like gvim and emacs. In order to use any graphical editor, it has to have a 'keep in foreground' option. I can't find any way of keeping a graphical program blocking in the foreground from a python subprocess call.
2. Termite seems to have a weird quoting issue that I would specifically have to code for to work around. Every other editor is successfully called like `<terminal> -e vim filename.txt`. For some reason termite has to have the whole -e argument quoted: `termite -e "vim filename.txt"`. There's already a bug report filed (https://github.com/thestinger/termite/issues/774) so I'm not intending on hacking in a fix.

Thanks for the interest! I'm going to close this for now. Let me know if you have more questions.
